version: 2
orbs:
  poetry: talkiq/poetry@4.0.0
jobs:

  plan-apply:
    name: Plan Terraform resources
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    name: Apply Terraform resources
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd terraform
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    name: Plan Terraform destroy resources
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd terraform
            terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .
    
  test:
    working_directory: /tmp/project
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Install poetry
          command: pip install poetry==1.1.15
      - run:
          name: Install dependencias
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest
      # - run:
      #     name: Run tests
      #     command: |
      #       pytest
      - persist_to_workspace:
          root: .
          paths:
            - .


  destroy:
    name: Destroy Terraform resources
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd terraform
            terraform apply -auto-approve tfdestroy
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - test
      - plan-apply:
          requires:
            - test
      # - hold-apply:
      #     type: approval
      #     requires:
      #       - plan-apply
      - apply:
          requires:
            - plan-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - plan-destroy